// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Valdictions",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Valdictions",
            targets: ["AppModule"],
            bundleIdentifier: "org.jhhs.425326.Valdictions",
            teamIdentifier: "G8D93PLQUC",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .box),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .incomingNetworkConnections(),
                .outgoingNetworkConnections()
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/SvenTiigi/YoutubePlayerKit.git", "1.8.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "YouTubePlayerKit", package: "youtubeplayerkit")
            ],
            path: "."
        )
    ]
)